services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'Root2147'
      MYSQL_DATABASE: web
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      # support chinese
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init_web.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: web
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge